// Code generated by protoc-gen-go. DO NOT EDIT.
// source: clipboard.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Clip struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clip) Reset()         { *m = Clip{} }
func (m *Clip) String() string { return proto.CompactTextString(m) }
func (*Clip) ProtoMessage()    {}
func (*Clip) Descriptor() ([]byte, []int) {
	return fileDescriptor_clipboard_57a42d2162a578a0, []int{0}
}
func (m *Clip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clip.Unmarshal(m, b)
}
func (m *Clip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clip.Marshal(b, m, deterministic)
}
func (dst *Clip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clip.Merge(dst, src)
}
func (m *Clip) XXX_Size() int {
	return xxx_messageInfo_Clip.Size(m)
}
func (m *Clip) XXX_DiscardUnknown() {
	xxx_messageInfo_Clip.DiscardUnknown(m)
}

var xxx_messageInfo_Clip proto.InternalMessageInfo

func (m *Clip) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PushRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRequest) Reset()         { *m = PushRequest{} }
func (m *PushRequest) String() string { return proto.CompactTextString(m) }
func (*PushRequest) ProtoMessage()    {}
func (*PushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clipboard_57a42d2162a578a0, []int{1}
}
func (m *PushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRequest.Unmarshal(m, b)
}
func (m *PushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRequest.Marshal(b, m, deterministic)
}
func (dst *PushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRequest.Merge(dst, src)
}
func (m *PushRequest) XXX_Size() int {
	return xxx_messageInfo_PushRequest.Size(m)
}
func (m *PushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRequest proto.InternalMessageInfo

func (m *PushRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clipboard_57a42d2162a578a0, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type SubscribeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_clipboard_57a42d2162a578a0, []int{3}
}
func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (dst *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(dst, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Clip)(nil), "Clip")
	proto.RegisterType((*PushRequest)(nil), "PushRequest")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*SubscribeRequest)(nil), "SubscribeRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClipboardClient is the client API for Clipboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClipboardClient interface {
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Clip, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Clip, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Clipboard_SubscribeClient, error)
}

type clipboardClient struct {
	cc *grpc.ClientConn
}

func NewClipboardClient(cc *grpc.ClientConn) ClipboardClient {
	return &clipboardClient{cc}
}

func (c *clipboardClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*Clip, error) {
	out := new(Clip)
	err := c.cc.Invoke(ctx, "/Clipboard/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipboardClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Clip, error) {
	out := new(Clip)
	err := c.cc.Invoke(ctx, "/Clipboard/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clipboardClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (Clipboard_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Clipboard_serviceDesc.Streams[0], "/Clipboard/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &clipboardSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Clipboard_SubscribeClient interface {
	Recv() (*Clip, error)
	grpc.ClientStream
}

type clipboardSubscribeClient struct {
	grpc.ClientStream
}

func (x *clipboardSubscribeClient) Recv() (*Clip, error) {
	m := new(Clip)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClipboardServer is the server API for Clipboard service.
type ClipboardServer interface {
	Push(context.Context, *PushRequest) (*Clip, error)
	Get(context.Context, *GetRequest) (*Clip, error)
	Subscribe(*SubscribeRequest, Clipboard_SubscribeServer) error
}

func RegisterClipboardServer(s *grpc.Server, srv ClipboardServer) {
	s.RegisterService(&_Clipboard_serviceDesc, srv)
}

func _Clipboard_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clipboard/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clipboard_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Clipboard/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clipboard_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClipboardServer).Subscribe(m, &clipboardSubscribeServer{stream})
}

type Clipboard_SubscribeServer interface {
	Send(*Clip) error
	grpc.ServerStream
}

type clipboardSubscribeServer struct {
	grpc.ServerStream
}

func (x *clipboardSubscribeServer) Send(m *Clip) error {
	return x.ServerStream.SendMsg(m)
}

var _Clipboard_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Clipboard",
	HandlerType: (*ClipboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _Clipboard_Push_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Clipboard_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Clipboard_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "clipboard.proto",
}

func init() { proto.RegisterFile("clipboard.proto", fileDescriptor_clipboard_57a42d2162a578a0) }

var fileDescriptor_clipboard_57a42d2162a578a0 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0xce, 0xc9, 0x2c,
	0x48, 0xca, 0x4f, 0x2c, 0x4a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x92, 0xe2, 0x62, 0x71,
	0xce, 0xc9, 0x2c, 0x10, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x09, 0x02, 0xb3, 0x95, 0x14, 0xb9, 0xb8, 0x03, 0x4a, 0x8b, 0x33, 0x82, 0x52, 0x0b, 0x4b,
	0x53, 0x8b, 0x4b, 0xb0, 0x2a, 0xe1, 0xe1, 0xe2, 0x72, 0x4f, 0x2d, 0x81, 0xaa, 0x50, 0x12, 0xe2,
	0x12, 0x08, 0x2e, 0x4d, 0x2a, 0x4e, 0x2e, 0xca, 0x4c, 0x4a, 0x85, 0x8a, 0x19, 0x15, 0x71, 0x71,
	0x3a, 0xc3, 0xec, 0x14, 0x92, 0xe5, 0x62, 0x01, 0x99, 0x28, 0xc4, 0xa3, 0x87, 0x64, 0xb0, 0x14,
	0xab, 0x1e, 0x48, 0x85, 0x12, 0x83, 0x90, 0x34, 0x17, 0xb3, 0x7b, 0x6a, 0x89, 0x10, 0xb7, 0x1e,
	0xc2, 0x4c, 0x84, 0xa4, 0x26, 0x17, 0x27, 0xdc, 0x70, 0x21, 0x41, 0x3d, 0x74, 0x8b, 0xe0, 0x0a,
	0x0d, 0x18, 0x9d, 0x58, 0xa2, 0x98, 0x0a, 0x92, 0x92, 0xd8, 0xc0, 0x3e, 0x34, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xea, 0xfc, 0x1b, 0x87, 0xf4, 0x00, 0x00, 0x00,
}
